// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Dropdown1 = lv_dropdown_create(ui_Screen3);
    lv_dropdown_set_options(ui_Dropdown1, "Auto\nCooling\nHeating\nDry");
    lv_obj_set_width(ui_Dropdown1, 155);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, 48);
    lv_obj_set_y(ui_Dropdown1, -19);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_align(ui_Dropdown1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Button4 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 250);
    lv_obj_set_y(ui_Button4, 51);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel2, 155);
    lv_obj_set_height(ui_Panel2, 86);
    lv_obj_set_x(ui_Panel2, 48);
    lv_obj_set_y(ui_Panel2, 62);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTemp = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp, -26);
    lv_obj_set_y(ui_LabelTemp, 1);
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemp, "25");
    lv_obj_set_style_text_font(ui_LabelTemp, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonTempUp = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_ButtonTempUp, 50);
    lv_obj_set_height(ui_ButtonTempUp, 37);
    lv_obj_set_x(ui_ButtonTempUp, 48);
    lv_obj_set_y(ui_ButtonTempUp, -20);
    lv_obj_set_align(ui_ButtonTempUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTempUp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonTempUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTempUp = lv_label_create(ui_ButtonTempUp);
    lv_obj_set_width(ui_LabelTempUp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempUp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTempUp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTempUp, "");
    lv_obj_set_style_text_font(ui_LabelTempUp, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonTempDown = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_ButtonTempDown, 50);
    lv_obj_set_height(ui_ButtonTempDown, 37);
    lv_obj_set_x(ui_ButtonTempDown, 48);
    lv_obj_set_y(ui_ButtonTempDown, 20);
    lv_obj_set_align(ui_ButtonTempDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTempDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonTempDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTempDown = lv_label_create(ui_ButtonTempDown);
    lv_obj_set_width(ui_LabelTempDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTempDown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTempDown, "");
    lv_obj_set_style_text_font(ui_LabelTempDown, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonACOn = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonACOn, 60);
    lv_obj_set_height(ui_ButtonACOn, 50);
    lv_obj_set_x(ui_ButtonACOn, -93);
    lv_obj_set_y(ui_ButtonACOn, -16);
    lv_obj_set_align(ui_ButtonACOn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonACOn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonACOn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelACOn = lv_label_create(ui_ButtonACOn);
    lv_obj_set_width(ui_LabelACOn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelACOn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelACOn, LV_ALIGN_CENTER);

    ui_ButtonACOff = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonACOff, 60);
    lv_obj_set_height(ui_ButtonACOff, 50);
    lv_obj_set_x(ui_ButtonACOff, -93);
    lv_obj_set_y(ui_ButtonACOff, 62);
    lv_obj_set_align(ui_ButtonACOff, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonACOff, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonACOff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelACOff = lv_label_create(ui_ButtonACOff);
    lv_obj_set_width(ui_LabelACOff, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelACOff, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelACOff, LV_ALIGN_CENTER);

    ui_Label4 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, -83);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "A/C");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonHome2 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonHome2, 57);
    lv_obj_set_height(ui_ButtonHome2, 44);
    lv_obj_set_x(ui_ButtonHome2, -5);
    lv_obj_set_y(ui_ButtonHome2, 5);
    lv_obj_set_align(ui_ButtonHome2, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ButtonHome2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonHome2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHome2 = lv_label_create(ui_ButtonHome2);
    lv_obj_set_width(ui_LabelHome2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHome2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHome2, 0);
    lv_obj_set_y(ui_LabelHome2, 1);
    lv_obj_set_align(ui_LabelHome2, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ButtonTempUp, ui_event_ButtonTempUp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonTempDown, ui_event_ButtonTempDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonHome2, ui_event_ButtonHome2, LV_EVENT_ALL, NULL);

}
