// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Home
void ui_Home_screen_init(void);
extern lv_obj_t * ui_Home;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Temperture;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Temperture1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Temperture2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
// CUSTOM VARIABLES
extern lv_obj_t * uic_sample;

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Button1;
void ui_event_SwitchLight(lv_event_t * e);
extern lv_obj_t * ui_SwitchLight;
void ui_event_ButtonHome1(lv_event_t * e);
extern lv_obj_t * ui_ButtonHome1;
extern lv_obj_t * ui_LabelHome1;
extern lv_obj_t * ui_Container1;
void ui_event_SliderBrightness(lv_event_t * e);
extern lv_obj_t * ui_SliderBrightness;
extern lv_obj_t * ui_LabelBrightness;
extern lv_obj_t * ui_Container2;
void ui_event_SliderColor(lv_event_t * e);
extern lv_obj_t * ui_SliderColor;
extern lv_obj_t * ui_LabelColor;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES
extern lv_obj_t * uic_aa;

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_ButtonHome2(lv_event_t * e);
extern lv_obj_t * ui_ButtonHome2;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_LabelTemp;
void ui_event_ButtonTempUp(lv_event_t * e);
extern lv_obj_t * ui_ButtonTempUp;
extern lv_obj_t * ui_LabelTempUp;
void ui_event_ButtonTempDown(lv_event_t * e);
extern lv_obj_t * ui_ButtonTempDown;
extern lv_obj_t * ui_LabelTempDown;
extern lv_obj_t * ui_ButtonACOn;
extern lv_obj_t * ui_ButtonACOff;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
void ui_event_ButtonHome3(lv_event_t * e);
extern lv_obj_t * ui_ButtonHome3;
extern lv_obj_t * ui_Container4;
void ui_event_SliderBrightness2(lv_event_t * e);
extern lv_obj_t * ui_SliderBrightness2;
extern lv_obj_t * ui_LabelBrightness2;
extern lv_obj_t * ui_Container6;
void ui_event_ButtonOpen(lv_event_t * e);
extern lv_obj_t * ui_ButtonOpen;
extern lv_obj_t * ui_LabelOpen;
void ui_event_ButtonStop(lv_event_t * e);
extern lv_obj_t * ui_ButtonStop;
extern lv_obj_t * ui_LabelStop;
void ui_event_ButtonClose(lv_event_t * e);
extern lv_obj_t * ui_ButtonClose;
extern lv_obj_t * ui_LabelClose;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_SpinboxTemp2;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
