// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonHome3 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_ButtonHome3, 57);
    lv_obj_set_height(ui_ButtonHome3, 44);
    lv_obj_set_x(ui_ButtonHome3, 129);
    lv_obj_set_y(ui_ButtonHome3, -98);
    lv_obj_set_align(ui_ButtonHome3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonHome3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonHome3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container4 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 302);
    lv_obj_set_height(ui_Container4, 50);
    lv_obj_set_x(ui_Container4, 0);
    lv_obj_set_y(ui_Container4, -12);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderBrightness2 = lv_slider_create(ui_Container4);
    lv_slider_set_value(ui_SliderBrightness2, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBrightness2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderBrightness2, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderBrightness2, 230);
    lv_obj_set_height(ui_SliderBrightness2, 17);
    lv_obj_set_x(ui_SliderBrightness2, -27);
    lv_obj_set_y(ui_SliderBrightness2, 0);
    lv_obj_set_align(ui_SliderBrightness2, LV_ALIGN_CENTER);


    ui_LabelBrightness2 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_LabelBrightness2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBrightness2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBrightness2, 117);
    lv_obj_set_y(ui_LabelBrightness2, 0);
    lv_obj_set_align(ui_LabelBrightness2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBrightness2, "50");
    lv_obj_set_style_text_color(ui_LabelBrightness2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBrightness2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBrightness2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 265);
    lv_obj_set_height(ui_Container6, 50);
    lv_obj_set_x(ui_Container6, 0);
    lv_obj_set_y(ui_Container6, 61);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonOpen = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_ButtonOpen, 60);
    lv_obj_set_height(ui_ButtonOpen, 50);
    lv_obj_set_x(ui_ButtonOpen, 90);
    lv_obj_set_y(ui_ButtonOpen, 0);
    lv_obj_set_align(ui_ButtonOpen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonOpen, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonOpen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelOpen = lv_label_create(ui_ButtonOpen);
    lv_obj_set_width(ui_LabelOpen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOpen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelOpen, LV_ALIGN_CENTER);

    ui_ButtonStop = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_ButtonStop, 60);
    lv_obj_set_height(ui_ButtonStop, 50);
    lv_obj_set_align(ui_ButtonStop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonStop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelStop = lv_label_create(ui_ButtonStop);
    lv_obj_set_width(ui_LabelStop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelStop, LV_ALIGN_CENTER);

    ui_ButtonClose = lv_btn_create(ui_Container6);
    lv_obj_set_width(ui_ButtonClose, 60);
    lv_obj_set_height(ui_ButtonClose, 50);
    lv_obj_set_x(ui_ButtonClose, -90);
    lv_obj_set_y(ui_ButtonClose, 0);
    lv_obj_set_align(ui_ButtonClose, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonClose, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonClose, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelClose = lv_label_create(ui_ButtonClose);
    lv_obj_set_width(ui_LabelClose, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelClose, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelClose, LV_ALIGN_CENTER);

    ui_Label7 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, -83);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Curtain");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonHome3, ui_event_ButtonHome3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderBrightness2, ui_event_SliderBrightness2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonOpen, ui_event_ButtonOpen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonStop, ui_event_ButtonStop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonClose, ui_event_ButtonClose, LV_EVENT_ALL, NULL);

}
