// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: alcedo-hub-gui

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern lv_obj_t * ui_Home;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Temperture;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Temperture1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Temperture2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
// CUSTOM VARIABLES
extern lv_obj_t * uic_sample;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

