// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: alcedo-hub-gui

#ifndef UI_SCREENAIRCON_H
#define UI_SCREENAIRCON_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenAircon
extern void ui_ScreenAircon_screen_init(void);
extern void ui_ScreenAircon_screen_destroy(void);
extern lv_obj_t * ui_ScreenAircon;
extern void ui_event_DropdownACMode(lv_event_t * e);
extern lv_obj_t * ui_DropdownACMode;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_LabelTemp;
extern void ui_event_ButtonTempUp(lv_event_t * e);
extern lv_obj_t * ui_ButtonTempUp;
extern lv_obj_t * ui_LabelTempUp;
extern void ui_event_ButtonTempDown(lv_event_t * e);
extern lv_obj_t * ui_ButtonTempDown;
extern lv_obj_t * ui_LabelTempDown;
extern void ui_event_ButtonACOn(lv_event_t * e);
extern lv_obj_t * ui_ButtonACOn;
extern lv_obj_t * ui_LabelACOn;
extern void ui_event_ButtonACOff(lv_event_t * e);
extern lv_obj_t * ui_ButtonACOff;
extern lv_obj_t * ui_LabelACOff;
extern lv_obj_t * ui_Label4;
extern void ui_event_ButtonHome2(lv_event_t * e);
extern lv_obj_t * ui_ButtonHome2;
extern lv_obj_t * ui_LabelHome2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

