// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -440);
    lv_obj_set_y(ui_Button1, 3);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SwitchLight = lv_switch_create(ui_Screen2);
    lv_obj_set_width(ui_SwitchLight, 109);
    lv_obj_set_height(ui_SwitchLight, 50);
    lv_obj_set_x(ui_SwitchLight, 0);
    lv_obj_set_y(ui_SwitchLight, -21);
    lv_obj_set_align(ui_SwitchLight, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_SwitchLight, lv_color_hex(0xFFD467), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SwitchLight, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_ButtonHome1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonHome1, 57);
    lv_obj_set_height(ui_ButtonHome1, 44);
    lv_obj_set_x(ui_ButtonHome1, -5);
    lv_obj_set_y(ui_ButtonHome1, 5);
    lv_obj_set_align(ui_ButtonHome1, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ButtonHome1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonHome1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHome1 = lv_label_create(ui_ButtonHome1);
    lv_obj_set_width(ui_LabelHome1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHome1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHome1, 0);
    lv_obj_set_y(ui_LabelHome1, 1);
    lv_obj_set_align(ui_LabelHome1, LV_ALIGN_CENTER);

    ui_Container1 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 302);
    lv_obj_set_height(ui_Container1, 50);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, 35);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderBrightness = lv_slider_create(ui_Container1);
    lv_slider_set_value(ui_SliderBrightness, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBrightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderBrightness, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderBrightness, 230);
    lv_obj_set_height(ui_SliderBrightness, 17);
    lv_obj_set_x(ui_SliderBrightness, -27);
    lv_obj_set_y(ui_SliderBrightness, 0);
    lv_obj_set_align(ui_SliderBrightness, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_SliderBrightness, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBrightness, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderBrightness, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SliderBrightness, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LabelBrightness = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_LabelBrightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBrightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBrightness, 117);
    lv_obj_set_y(ui_LabelBrightness, 0);
    lv_obj_set_align(ui_LabelBrightness, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBrightness, "50");
    lv_obj_set_style_text_color(ui_LabelBrightness, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBrightness, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 316);
    lv_obj_set_height(ui_Container2, 50);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, 83);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderColor = lv_slider_create(ui_Container2);
    lv_slider_set_value(ui_SliderColor, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderColor) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderColor, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderColor, 230);
    lv_obj_set_height(ui_SliderColor, 17);
    lv_obj_set_x(ui_SliderColor, -27);
    lv_obj_set_y(ui_SliderColor, 0);
    lv_obj_set_align(ui_SliderColor, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_SliderColor, lv_color_hex(0xFFEEBC), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderColor, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderColor, lv_color_hex(0xFFD35A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SliderColor, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderColor, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderColor, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelColor = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_LabelColor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelColor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelColor, 117);
    lv_obj_set_y(ui_LabelColor, 0);
    lv_obj_set_align(ui_LabelColor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelColor, "50");
    lv_obj_set_style_text_color(ui_LabelColor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelColor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelColor, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -83);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Light");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SwitchLight, ui_event_SwitchLight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonHome1, ui_event_ButtonHome1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderBrightness, ui_event_SliderBrightness, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderColor, ui_event_SliderColor, LV_EVENT_ALL, NULL);
    uic_aa = ui_Button1;

}
