// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: alcedo-hub-gui

#ifndef UI_SCREENLIGHT_H
#define UI_SCREENLIGHT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenLight
extern void ui_ScreenLight_screen_init(void);
extern void ui_ScreenLight_screen_destroy(void);
extern lv_obj_t * ui_ScreenLight;
extern lv_obj_t * ui_Button1;
extern void ui_event_SwitchLight(lv_event_t * e);
extern lv_obj_t * ui_SwitchLight;
extern void ui_event_ButtonHome1(lv_event_t * e);
extern lv_obj_t * ui_ButtonHome1;
extern lv_obj_t * ui_LabelHome1;
extern lv_obj_t * ui_Container1;
extern void ui_event_SliderBrightness(lv_event_t * e);
extern lv_obj_t * ui_SliderBrightness;
extern lv_obj_t * ui_LabelBrightness;
extern lv_obj_t * ui_Container2;
extern void ui_event_SliderColor(lv_event_t * e);
extern lv_obj_t * ui_SliderColor;
extern lv_obj_t * ui_LabelColor;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES
extern lv_obj_t * uic_aa;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

