// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: alcedo-hub-gui

#ifndef UI_SCREENCURTAIN_H
#define UI_SCREENCURTAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenCurtain
extern void ui_ScreenCurtain_screen_init(void);
extern void ui_ScreenCurtain_screen_destroy(void);
extern lv_obj_t * ui_ScreenCurtain;
extern lv_obj_t * ui_Container4;
extern void ui_event_SliderOpen(lv_event_t * e);
extern lv_obj_t * ui_SliderOpen;
extern lv_obj_t * ui_LabelOpenSlider;
extern lv_obj_t * ui_Container6;
extern void ui_event_ButtonOpen(lv_event_t * e);
extern lv_obj_t * ui_ButtonOpen;
extern lv_obj_t * ui_LabelOpen;
extern void ui_event_ButtonStop(lv_event_t * e);
extern lv_obj_t * ui_ButtonStop;
extern lv_obj_t * ui_LabelStop;
extern void ui_event_ButtonClose(lv_event_t * e);
extern lv_obj_t * ui_ButtonClose;
extern lv_obj_t * ui_LabelClose;
extern lv_obj_t * ui_Label7;
extern void ui_event_ButtonHome3(lv_event_t * e);
extern lv_obj_t * ui_ButtonHome3;
extern lv_obj_t * ui_LabelHome3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

