// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void SwitchLightClicked(lv_event_t * e);
void SliderBrightnessChanged(lv_event_t * e);
void SliderColorChanged(lv_event_t * e);
void DropdownACModeChanged(lv_event_t * e);
void ButtonTempUpClicked(lv_event_t * e);
void ButtonTempDownClicked(lv_event_t * e);
void ButtonACOnClickerd(lv_event_t * e);
void ButtonACOffClicked(lv_event_t * e);
void SliderOpenChanged(lv_event_t * e);
void ButtonOpenClicked(lv_event_t * e);
void ButtonStopClicked(lv_event_t * e);
void ButtonCloseClicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
