// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void SwitchLightClicked(lv_event_t * e)
{
	// Your code here
}

void SliderBrightnessChanged(lv_event_t * e)
{
	// Your code here
}

void SliderColorChanged(lv_event_t * e)
{
	// Your code here
}

void DropdownACModeChanged(lv_event_t * e)
{
	// Your code here
}

void ButtonTempUpClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonTempDownClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonACOnClickerd(lv_event_t * e)
{
	// Your code here
}

void ButtonACOffClicked(lv_event_t * e)
{
	// Your code here
}

void SliderOpenChanged(lv_event_t * e)
{
	// Your code here
}

void ButtonOpenClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonStopClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonCloseClicked(lv_event_t * e)
{
	// Your code here
}
