// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SpinboxTemp2 = lv_spinbox_create(ui_Screen5);
    lv_obj_set_width(ui_SpinboxTemp2, 118);
    lv_obj_set_height(ui_SpinboxTemp2, 64);
    lv_obj_set_x(ui_SpinboxTemp2, -56);
    lv_obj_set_y(ui_SpinboxTemp2, 78);
    lv_obj_set_align(ui_SpinboxTemp2, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_SpinboxTemp2, 3, 2);
    lv_spinbox_set_range(ui_SpinboxTemp2, 0, 9999);
    lv_spinbox_set_cursor_pos(ui_SpinboxTemp2, 1 - 1);
    lv_spinbox_set_value(ui_SpinboxTemp2, 123);
    lv_obj_set_style_text_color(ui_SpinboxTemp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpinboxTemp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SpinboxTemp2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpinboxTemp2, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SpinboxTemp2, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpinboxTemp2, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SpinboxTemp2, lv_color_hex(0xF3F3F3), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpinboxTemp2, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_SpinboxTemp2, LV_TEXT_DECOR_UNDERLINE, LV_PART_CURSOR | LV_STATE_DEFAULT);


}
